### 1. Preparing the text data & 2. Creating dictionary

Using the example codes given in the courseware.

In [1]:
from collections import Counter
import os

def make_Dictionary(train_dir):
    emails = [os.path.join(train_dir,f) for f in os.listdir (train_dir)]
    all_words = []
    for mail in emails:
        with open (mail) as m:
            for i,line in enumerate (m) :
                if i == 2:
                    words = line.split()
                    all_words += words
    dictionary = Counter(all_words)
    
    list_to_remove = list(dictionary.keys())
    for item in list_to_remove:
        if item.isalpha() == False:
            del dictionary[item]
        elif len(item) == 1:
            del dictionary[item]
    dictionary = dictionary.most_common(3000)
    
    return dictionary

In [2]:
dictionary = make_Dictionary('ling-spam/train-mails')
dictionary

[('order', 1414),
 ('address', 1293),
 ('report', 1216),
 ('mail', 1127),
 ('send', 1079),
 ('language', 1072),
 ('email', 1051),
 ('program', 1001),
 ('our', 987),
 ('list', 935),
 ('one', 917),
 ('name', 878),
 ('receive', 826),
 ('money', 788),
 ('free', 762),
 ('work', 755),
 ('information', 677),
 ('business', 654),
 ('please', 652),
 ('university', 595),
 ('us', 564),
 ('day', 556),
 ('follow', 544),
 ('internet', 520),
 ('over', 511),
 ('http', 479),
 ('check', 472),
 ('call', 469),
 ('each', 466),
 ('include', 452),
 ('com', 448),
 ('linguistic', 442),
 ('number', 423),
 ('want', 420),
 ('letter', 419),
 ('need', 418),
 ('many', 412),
 ('here', 397),
 ('market', 395),
 ('start', 390),
 ('even', 386),
 ('fax', 383),
 ('form', 380),
 ('most', 377),
 ('first', 373),
 ('web', 366),
 ('service', 363),
 ('interest', 362),
 ('software', 352),
 ('remove', 349),
 ('read', 347),
 ('those', 345),
 ('week', 344),
 ('every', 332),
 ('credit', 329),
 ('ll', 326),
 ('site', 320),
 ('much', 31

### 3. Feature Extraction
Using the example codes given in the courseware.

In [3]:
import numpy as np
def extract_features(mail_dir):
    files = [os.path.join(mail_dir,fi) for fi in os.listdir(mail_dir)]
    features_matrix = np.zeros((len(files),3000))
    docID = 0
    _i = 0
    print(len(files))
    for fil in files:
        _i+=1
        with open(fil) as fi:
            for i,line in enumerate(fi):
                if i == 2:
                    words = line.split()
                    for word in words:
                        wordID = 0
                        for i,d in enumerate(dictionary):
                            if d[0] == word:
                                wordID = i
                                features_matrix[docID,wordID]+=1
            docID = docID + 1
        print('\r','done {} files'.format(_i),flush=True,end='')
    return features_matrix

In [4]:
# Create a dictionary of words with its frequency
features_matrix = extract_features("ling-spam/train-mails")
features_matrix

702
 done 702 filesone 39 files

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

### 4. Training the Classifier: Preparing Dataset
Using the example codes given in the courseware.

In [5]:
# Prepare feature vectors per training mail and its labels

X_train = features_matrix[:]
# Counted the number of normal & spam mails
y_train = np.append(np.zeros(351), np.ones(351))

X_train, y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [6]:
# Prepare feature vectors per testing mail and its labels

X_test = extract_features("ling-spam/test-mails")[:]
y_test = np.append(np.zeros(130), np.ones(130))

X_test, y_test

260
 done 260 files

(array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  1.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [17.,  2.,  0., ...,  0.,  0.,  0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

### 5. Training the Classifier: Implementation of the Naive Bayes algorithm

NOT using the courseware codes, for that they don't perform well.

Partly referred to the codes in the SKlearn GaussianNB Class and online blogs, but mostly original.

In [7]:
import numpy as np
import collections
import math
class MyGaussianNB():
    def __init__(self):
        self.map = {}
        self.vars = None
        self.means = None
        self.epsilon = None
        self.smoothing = None
        self.class_num = None
        self.class_prior= None

    def fit(self, X, Y, smoothing = 1e-9):
        cnt = collections.Counter(Y)
        self.class_num = 0
        
        for k, v in cnt.items():
            self.map[k] = self.class_num
            self.class_num += 1
        
        self.class_prior = np.array([ v / len(Y) for k, v in cnt.items()])
        
        new_y =np.array([self.map[i] for i in Y])
        self.means = np.array([X[new_y == id].mean(axis=0) for id in range(self.class_num)])
        
        new_y = np.array([self.map[i] for i in Y])
        self.vars = np.array([X[new_y == id].var(axis=0) for id in range(self.class_num)])
        
        self.smoothing = smoothing
        self.epsilon = self.smoothing * self.vars.max()
        self.vars = self.vars + self.epsilon

    def gaussian(self, x, u, var):
        return -(x - u) ** 2 / (2 * var) - math.log(math.sqrt(2 * math.pi * var))
    
    def predict(self, X):
        predictions = []
        result = 0
        
        for x in X:
            temp = 0.0
            dims = len(x)
            log_prior = np.log(self.class_prior)
            for id in range(self.class_num):
                likelihood = np.sum([self.gaussian(x[j], self.means[id][j], self.vars[id][j]) for j in range(dims)])
                prob = log_prior[id] + likelihood
                if prob > temp:
                    temp = prob
                    result = id
            predictions.append(result)
        
        return predictions

In [8]:
'''
    # Deprecated implementation
    # Derived from courseware modules
    # Not performing well

class NaiveBayes():

    def fit(self, X, y, smoothing):
        y = y.astype(int)
        self.X = X
        self.y = y
        self.classes = np.unique(y)
        self.parameters = {}
        maxVar = 0
        for i, c in enumerate(self.classes):
            # Calculate the mean, variance, prior probability of each class
            X_Index_c = X[np.where(y == c)]
            X_index_c_mean = np.mean(X_Index_c, axis=0, keepdims=True)[0]
            X_index_c_var = np.var(X_Index_c, axis=0, keepdims=True)[0]
            parameters = {"mean": X_index_c_mean, "var": X_index_c_var, "prior": X_Index_c.shape[0] / X.shape[0]}
            if parameters["var"].max() > maxVar:
                maxVar = parameters["var"].max()
            self.parameters[c] = parameters
        # Smoothing
        self.epsilon = smoothing * maxVar

    def gaussian(self, x, u, var):
        newVar = var + self.epsilon
        return -(x - u) ** 2 / (2 * newVar) - math.log(math.sqrt(2 * math.pi * newVar))

    def predict(self, X):
        predictions = []
        
        for x in X:
            # return class with highest probability
            dims = len(x)
            likelihoods = []
            log_class_prior = []
            temp = 0.0
            result = 0
            for id in range(len(self.classes)):
                likelihoods = np.sum([self.gaussian(x[j], self.parameters[id]["mean"][j], self.parameters[id]["var"][j]) for j in range(dims)])
                log_class_prior = np.log(self.parameters[id]["prior"])
                all_pros = log_class_prior + likelihoods

                if all_pros > temp:
                    temp = all_pros
                    result = id
            
            predictions.append(result)
            # Complete code for naive Bayes algorithm
        
        return predictions'''

'\n    # Deprecated implementation\n    # Derived from courseware modules\n    # Not performing well\n\nclass NaiveBayes():\n\n    def fit(self, X, y, smoothing):\n        y = y.astype(int)\n        self.X = X\n        self.y = y\n        self.classes = np.unique(y)\n        self.parameters = {}\n        maxVar = 0\n        for i, c in enumerate(self.classes):\n            # Calculate the mean, variance, prior probability of each class\n            X_Index_c = X[np.where(y == c)]\n            X_index_c_mean = np.mean(X_Index_c, axis=0, keepdims=True)[0]\n            X_index_c_var = np.var(X_Index_c, axis=0, keepdims=True)[0]\n            parameters = {"mean": X_index_c_mean, "var": X_index_c_var, "prior": X_Index_c.shape[0] / X.shape[0]}\n            if parameters["var"].max() > maxVar:\n                maxVar = parameters["var"].max()\n            self.parameters[c] = parameters\n        # Smoothing\n        self.epsilon = smoothing * maxVar\n\n    def gaussian(self, x, u, var):\n    

In [9]:
from sklearn.metrics import confusion_matrix

model = MyGaussianNB()
model.fit(X_train, y_train)
result = model.predict(X_test)
print(confusion_matrix(y_test, result))

[[128   2]
 [  5 125]]


### 6. Checking the results
Deriving accuracy score, recall score, and f1 score from the results.

In [10]:
from sklearn.metrics import accuracy_score, recall_score, f1_score

accuracyScore = accuracy_score(y_test, result)
recallScore = recall_score(y_test, result)
f1Score = f1_score(y_test, result)

print("Accuracy Score:", accuracyScore)
print("Recall Score:", recallScore)
print("F1 Score:", f1Score)

Accuracy Score: 0.9730769230769231
Recall Score: 0.9615384615384616
F1 Score: 0.9727626459143969


### Exercise 2: Compare with SKlearn

My model outperforms the GaussianNB in SKlearn on all three scores. Hence I can conclude that my model performs better.

I at first consider that the reason why my model does better is the fortune. Namely, it does better only by chance. the reasons are as follow.

The Naive Bayes algorithm does not include randomlized factors. Hence, for the same model, the result is always the same with a constant input.

One step further, the Gaussian algorithm part of all Gaussian Naive Bayes algorithms should be the same, according to the definition of Gaussian distribution.

Specifically on this case, the input datasets are also the same for both mine and SKlearn's GaussianNB. The smoothing coefficients are identical, too.

**Hence, I do not see the point where the difference should come in between the two models.**

**Except for one step during the process. That is, finding the term with the largest possibility.** There might be plural (in this case, two) terms with possibilities that are identical or too close to be distinguishable for the program. Hence, the two models might choose different terms, belonging to different classes, leading to different results.

Though, in fact, when I inverts the priorities of the two classes to make my model choose another class when there are two identical possibilities, the outcome stays the same.

This to some extend disproves my first hypothesis.

Then, I can only suppose that there are more source codes in the SKlearn Package which **process the data more** for the model to perform well under more circumstances, which I didn't have time to look into more carefully. This should explain why my model does better on this dataset, as which is a tolerable error on the whole for a package that must be suitable under a large number of situations.

Or, simply the **floating point arithmetic error** between these two models is to blame.

In [11]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

newAc = accuracy_score(y_test, y_pred)
newRe = recall_score(y_test, y_pred)
newF1 = f1_score(y_test, y_pred)

print("SKlearn:")
print("Accuracy Score:", newAc)
print("Recall Score:", newRe)
print("F1 Score:", newF1)
print("My model:")
print("Accuracy Score:", accuracyScore)
print("Recall Score:", recallScore)
print("F1 Score:", f1Score)

SKlearn:
Accuracy Score: 0.9615384615384616
Recall Score: 0.9307692307692308
F1 Score: 0.9603174603174605
My model:
Accuracy Score: 0.9730769230769231
Recall Score: 0.9615384615384616
F1 Score: 0.9727626459143969


### Exercise 3 Questions

1. **Describe another real-world application where the naïve Bayes method can be applied.**
  - Classifying the major of students basing on the courses they take.

2. **What are the strengths of the naïve Bayes method; when does it perform well?**
  - It is derived from the Classical Probability Spaces, with a stable performance.
  - It can deal with incremental tasks, hence is friendly to computing power resources.
  - It is easy to implement.

  It performs well on datasets that are with independent features, which conform to its basic assumption.

3. **What are the weaknesses of the naïve Bayes method; when does it perform poorly?**
  - It assumes that features of the dataset are indepdent, which usually does not hold under production environments.
  - Relies on prior probability, which is often hard to decide.

  It performs poorly on datasets that contain strongly related features, and when the prior model is not suitable.

4. **What makes the naïve Bayes method a good candidate for the classification problem, if you have enough knowledge about the data?**
  - If we know that the features in the dataset are likely independent, then the naive Bayes method can be a good candidate for that it is easy to implement, fast to train, accurate on classifying, and stable on performance. All these advantages make it fast, reliable, and cost-effective in production.