# LAB7 Assignment
> The document description are designed by JIa Yanhong in 2022. Oct. 20th
------

## LAB Assignment
### Exercise 1 logistic regression (20 points )
This exercise uses dataset digit01.csv , which has 13 columns, and the last column is the dependent variable. 

This part requires you to implement a `logistic regression` using the pytorch framework (defining a logistic regression class that inherits `nn.module`). To test your model, we provide a dataset `digit01.csv` which is in the **datasets folder**. This dataset requires you to divide the training set and the test set by yourself, and it is recommended that 80% of the training set and 20% of the test set be used.

+ load datasets

In [670]:
########### Write Your Code Here ###########
import numpy as np

import warnings
warnings.filterwarnings("ignore") 

data = np.loadtxt("datasets/digit01.csv", dtype='int', delimiter=',')
print(data)
############################################

[[1 1 1 1 0 1 1 0 1 1 1 1 0]
 [0 1 1 1 0 1 1 0 1 1 1 1 0]
 [1 1 0 1 0 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 0 1 1 1 0 0]
 [1 1 1 1 0 1 1 0 1 0 1 1 0]
 [0 0 0 1 1 1 1 0 1 1 1 1 0]
 [0 0 0 0 1 1 1 0 1 1 1 1 0]
 [0 0 0 1 1 0 1 0 1 1 1 1 0]
 [0 0 0 1 1 1 1 0 1 1 1 0 0]
 [0 0 0 1 1 1 1 0 1 0 1 1 0]
 [1 1 1 1 0 1 1 1 1 0 0 0 0]
 [0 1 1 1 0 1 1 1 1 0 0 0 0]
 [1 1 0 1 0 1 1 1 1 0 0 0 0]
 [1 1 1 1 0 1 1 1 0 0 0 0 0]
 [1 1 1 1 0 1 0 1 1 0 0 0 0]
 [1 0 1 1 0 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 0 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 0 0 1 1 1 0]
 [1 1 1 1 0 1 1 0 1 1 0 1 0]
 [1 1 1 1 0 1 0 0 1 1 1 1 0]
 [1 1 1 0 0 1 1 0 1 1 1 1 0]
 [0 0 1 1 0 1 1 0 1 1 1 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 1 0]
 [0 1 1 1 0 1 1 0 0 1 1 1 0]
 [0 1 1 1 0 1 1 0 1 1 0 1 0]
 [0 1 1 1 0 1 0 0 1 1 1 1 0]
 [0 1 1 0 0 1 1 0 1 1 1 1 0]
 [1 1 0 1 0 0 1 0 1 1 1 1 0]
 [1 1 0 1 0 1 1 0 0 1 1 1 0]
 [1 1 0 1 0 1 1 0 1 1 0 1 0]
 [1 1 0 1 0 1 0 0 1 1 1 1 0]
 [1 1 0 0 0 1 1 0 1 1 1 1 0]
 [0 1 0 0 1 0 0 1 0 0 1 0 1]
 [1 1 0 0 1 0 0 1 0 0 1 0 1]
 [0 1 0 0 1 0 

+ Splitting dataset into 80% Training and 20% Testing Data:

In [671]:
########### Write Your Code Here ###########
from sklearn.model_selection import train_test_split


X = data[:, :-1]
y = data[:, -1]
#print(X)
#print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=41)
print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)

import  torch
X_train, X_test = torch.Tensor(X_train), torch.Tensor(X_test)
y_train, y_test = torch.Tensor(y_train), torch.Tensor(y_test)
############################################

X_train: [[1 1 1 1 0 1 1 1 1 0 0 0]
 [1 1 0 1 0 1 1 0 1 1 0 1]
 [0 0 0 1 1 1 1 0 1 1 1 0]
 [1 0 1 1 0 1 1 0 1 1 1 1]
 [1 1 0 0 1 1 0 1 0 0 1 0]
 [1 1 0 1 0 0 1 0 1 1 1 1]
 [0 1 1 0 1 1 0 1 1 0 1 1]
 [1 1 1 1 0 1 0 1 1 0 0 0]
 [1 1 0 1 0 1 1 0 1 1 1 1]
 [1 1 0 1 0 1 0 0 1 1 1 1]
 [0 0 0 1 1 0 1 0 1 1 1 1]
 [1 1 0 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 1 1 0 1 1 0 1 1]
 [0 0 0 1 1 1 1 0 1 1 1 1]
 [1 1 0 0 1 0 0 1 0 0 1 0]
 [1 1 0 1 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 0 1 1 0 1]
 [1 1 0 0 1 0 0 1 0 1 1 1]
 [0 1 0 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 1 1 0]
 [1 1 1 1 0 1 1 0 1 0 1 1]
 [1 1 0 0 0 1 1 0 1 1 1 1]
 [1 1 1 1 0 1 1 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 1 1 1 1]
 [1 1 0 1 1 0 1 1 0 1 1 0]
 [0 1 0 0 1 1 0 1 0 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 0 0 1 1 1]
 [0 1 0 0 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 1 1 1 1 0 0 0]
 [0 1 1 1 0 1 1 0 1 1 0 1]
 [1 1 0 1 0 1 1 0 0 1 1 1]
 [0 1 0 0 1 0 0 1 1 0 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 1]
 [1 1 1 0 0 1 1 0 1 1 1 1]
 [0 0 0 0 1 1 1 0 1 1 1 1]
 [0 1 0 0 0 1 0 0 1

+ Define a LogisticRegression subclass of nn. Module

In [672]:
# Define a LogisticRegression subclass of nn. Module.
########### Write Your Code Here ###########
class LogisticRegression(torch.nn.Module):
     def __init__(self, input_dim, output_dim):
         super(LogisticRegression, self).__init__()
         self.linear = torch.nn.Linear(input_dim, output_dim)

     def forward(self, x):
         return torch.sigmoid(self.linear(x))
############################################

+ Create the model

In [673]:

########### Write Your Code Here ###########
epochs = 10000
input_dim = 12
output_dim = 1
learning_rate = 0.01

model = LogisticRegression(input_dim, output_dim)
############################################

 + Loss function

In [674]:
########### Write Your Code Here ###########
criterion = torch.nn.BCELoss()
############################################

+ The optimizer

In [675]:
########### Write Your Code Here ###########
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
############################################

+ training Model

In [676]:
########### Write Your Code Here ###########
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(torch.squeeze(outputs), y_train) 
    loss.backward()
    optimizer.step()
    if epoch % 1000 == 0:
        print(f'epoch: {epoch}, loss = {loss.item():.4f}')
############################################

epoch: 0, loss = 0.6622
epoch: 1000, loss = 0.1502
epoch: 2000, loss = 0.0919
epoch: 3000, loss = 0.0685
epoch: 4000, loss = 0.0554
epoch: 5000, loss = 0.0469
epoch: 6000, loss = 0.0410
epoch: 7000, loss = 0.0365
epoch: 8000, loss = 0.0329
epoch: 9000, loss = 0.0301



+ Model Performance


In [677]:
########### Write Your Code Here ###########
with torch.no_grad():
    logits = model(X_test)
    y_pred = torch.nn.Softmax(dim=1)(logits)
    #print(logits)
    #print(y_pred)
    count = 0
    for i in range(len(y_pred)):
        if y_pred[i] == y_test[i]:
            count += 1
    acc = count / float(y_test.shape[0])
    print(f'accuracy: {acc:.4f}')
############################################

accuracy: 0.9231


In [652]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       0.92      1.00      0.96        12

    accuracy                           0.92        13
   macro avg       0.46      0.50      0.48        13
weighted avg       0.85      0.92      0.89        13



### Exercise 2  Handwriting recognition with MLP

Like last week's lab , your task in this section is also about recognizing handwritten digits, but you are required to use MLP to complete the exercise. It is recommended that you define an MLP class, which is a subclass of `nn.module`.

<font color='red' size=4>Note that your accuracy in this section will directly determine your score.</font>

For this exercise we use the `minist` dataset.

+ load datasets

In [653]:
########### Write Your Code Here ###########
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore") 


import struct
import numpy as np


labels_path = "datasets/MNIST/raw/train-labels-idx1-ubyte"
images_path = "datasets/MNIST/raw/train-images-idx3-ubyte"
with open(labels_path, 'rb') as lbpath:
    magic, n = struct.unpack('>II',lbpath.read(8))
    train_labels = np.fromfile(lbpath,dtype=np.uint8)
with open(images_path, 'rb') as imgpath:
    magic, num, rows, cols = struct.unpack('>IIII',imgpath.read(16))
    train_images = np.fromfile(imgpath,dtype=np.uint8).reshape(len(train_labels), 784)

labels_path = "datasets/MNIST/raw/t10k-labels-idx1-ubyte"
images_path = "datasets/MNIST/raw/t10k-images-idx3-ubyte"
with open(labels_path, 'rb') as lbpath:
    magic, n = struct.unpack('>II',lbpath.read(8))
    test_labels = np.fromfile(lbpath,dtype=np.uint8)
with open(images_path, 'rb') as imgpath:
    magic, num, rows, cols = struct.unpack('>IIII',imgpath.read(16))
    test_images = np.fromfile(imgpath,dtype=np.uint8).reshape(len(test_labels), 784)


train_images = train_images / 255.0
test_images = test_images / 255.0
train_labels = train_labels
test_labels = test_labels
############################################

+ Define a MLP subclass of nn. Module

In [654]:
########### Write Your Code Here ###########
class MLP(torch.nn.Module):
  def __init__(self, size, hidden=200, classes=10):
    super(MLP, self).__init__()
    self.layer1=torch.nn.Linear(size, hidden)
    self.relu1=torch.nn.ReLU()
    self.layer2=torch.nn.Linear(hidden, classes)
    self.relu2=torch.nn.ReLU()

  def forward(self, input):
    out=self.layer1(input)
    out=self.relu1(out)
    out=self.layer2(out)
    out=self.relu2(out)
    return out
############################################

+ Create the model

In [655]:
########### Write Your Code Here ###########
num_epochs = 15
learning_rate = 0.0045

models = MLP(784)
############################################

 + Loss function

In [656]:
########### Write Your Code Here ###########
criterions = torch.nn.CrossEntropyLoss()
############################################

+ The optimizer

In [657]:
########### Write Your Code Here ###########
optimizers = torch.optim.SGD(models.parameters(), lr=learning_rate)
############################################

+ training Model

In [658]:

########### Write Your Code Here ###########
models.train()
for epoch in range(num_epochs):
    tot_loss = 0
    for i in range(len(train_images)):
        optimizers.zero_grad()
        y_pred = models(torch.from_numpy(train_images[i]).float())
        y_test = np.zeros((10), dtype=float)
        y_test[train_labels[i]] = 1.0
        loss = criterions(y_pred, torch.tensor(y_test))
        loss.backward()
        optimizers.step()
        tot_loss += loss.item()
        if i % 10000 == 0:
            print(loss.item())
    print(f'epoch: {epoch+1}, loss = {tot_loss/len(train_images):.4f}')
############################################

2.3452491760253906
2.3025851249694824
0.0011016021016985178
2.3025851249694824
0.0014865073608234525
2.3025851249694824
epoch: 1, loss = 0.9969
0.07321454584598541
2.3025851249694824
0.00011932138295378536
2.3025851249694824
0.00019774865359067917
2.3025851249694824
epoch: 2, loss = 0.8148
0.011064130812883377
2.3025851249694824
7.390948667307384e-06
0.51663738489151
9.16677454370074e-05
0.011759838089346886
epoch: 3, loss = 0.5157
0.008998436853289604
0.0003477922291494906
7.629365427419543e-06
0.00770264957100153
6.067568756407127e-05
0.003700672183185816
epoch: 4, loss = 0.3170
0.0035527939908206463
0.00014494798961095512
1.5497195136049413e-06
0.006106528919190168
3.6000557884108275e-05
0.0009314250783063471
epoch: 5, loss = 0.2958
0.006441781297326088
5.566918844124302e-05
1.1920922133867862e-06
0.004911263473331928
3.814624506048858e-05
0.00038521020906046033
epoch: 6, loss = 0.2825
0.0063132611103355885
2.253030106658116e-05
9.536738616588991e-07
0.003366875695064664
2.503363793

+ Model Performance

In [667]:
########### Write Your Code Here ###########
y_predicted_cls = []
models.eval()
with torch.no_grad():
    correct = 0
    for i in range(len(test_images)):
        y_pred  = models(torch.from_numpy(test_images[i]).float())
        if torch.argmax(y_pred) == test_labels[i]:
            correct += 1
        y_predicted_cls.append(torch.argmax(y_pred))
    print('Accuracy:', correct / len(test_images))
############################################

Accuracy: 0.9787


In [668]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predicted_cls))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.98      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.98      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.96      0.99      0.98       892
           6       0.99      0.97      0.98       958
           7       0.99      0.96      0.98      1028
           8       0.98      0.97      0.97       974
           9       0.96      0.98      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



### Exercise 3  Questions (10 points )
1.What's the difference between logistic regression and Perceptron?

    - `Their loss functions are different. Logistic Regression is maximizing the MLE, Perceptron is minimizing the sum of the distances of incorrect outputs.`
    - `Their activate functions are different. Perceptron uses a step function while Logistic Regression uses a sigmoid funciton.`

2.Advantages and disadvantages of neural networks?

    `Advantages:`
      - `Neural Networks improve their performance largely according to the size of dataset, while traditional algorithms stops improving when the dataset size becomes larger and larger. Hence Neural Networks outperform when the training set is large enough.`
      - `Different Neural Networks are friendly to supervised or unsupervised scenarios, nearly all engineering problems can be fit into this framework.`
      - `Neural Networks are relatively easy to scale, and can handle large size of features without lossing accuracy.`
    `Disadvantages:`
      - `Neural Networks are black boxes. Most of them are not very explainable, making them unsuitable for fields where decisions need to be reasonable for humans.`
      - `A good Neural Network requires lots of time to train and tune. And for that they are not very explainable, this process can be desperately difficult.`
      - `Neural Networks need large size of data. For scenarios with few data, they are not suitable.`

3.What is the role of Activation Function in Neural networks?

    `Activation Function is responsible for introducing non-linear activations to the model, hence making it more suitable for complex real-life scenarios. Otherwise the Neural Networks are only combinations of linear functions, which can only cut edges with more and more linear functions to approach the curve. Activation Functions make this easier and straight-forward.`